language: php
sudo: false
php:
  - '7.0'
  - '7.1'
  - '7.2'
before_install:
  - travis_retry composer self-update --preview
install:
  - travis_retry composer install --no-interaction --prefer-dist
script:
  - php vendor/bin/phpunit